version: 2

sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub

build:
  image: testing

python:
  version: 3.9
  system_packages: False
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
