language: python

# Only run tests on push on a few branches.
# Test on PR should be execute for all branches and forks.
branches:
  only:
  - master

python:
  - 2.7

env:
  - TOX_ENV=py27-test-twlatest
  - TOX_ENV=py27-test-twtrunk
  - TOX_ENV=py34-test-twtrunk
  - TOX_ENV=linters

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py34-test-twtrunk

install:
  - pip install tox coveralls codecov

script:
  - tox -e $TOX_ENV

after_script:
  - codecov
  - coveralls

notifications:
    email: false
