[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ldaptor"
author = "Tommi Virtanen"
author-email = "tv@eagain.net"
home-page = "https://github.com/twisted/ldaptor"
description-file = "README.rst"
