#
# Release to PyPi on a new tag.
#
# No tests are executed before a release.
#
name: PyPi

on: [push]

jobs:

  build-and-publish:
    name: Build source and wheel. Publish on new tag.
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Get the code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install deps
      run: >-
        python -m
        pip install
        tox
        --user
    - name: Build a binary wheel and a source tarball
      run: tox -e release

    - name: Publish to PyPI for a new tag
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.3.1
      with:
        password: ${{ secrets.PYPI_GITHUB_PACKAGE_UPLOAD }}
